### ISSUE TITLE
JSON reading error From api.uri 

### ISSUE THREAD

**Issue by LaiZhou** [julianxhokaxhiu/LineageOTA#72]
It' my public ota uri:
`
https://ota.xunt123.com/api
`
the api request returns response:
`
{
    "id": null,
    "result": [
        {
            "incremental": "",
            "api_level": "",
            "url": "https://ota.xunt123.com//builds/full/lineage-17.1-20210420-UNOFFICIAL-chiron.zip",
            "timestamp": 1618754135,
            "md5sum": "2de1555284dc81423a2210dbec4e0fce",
            "changes": "",
            "channel": "unofficial",
            "filename": "lineage-17.1-20210420-UNOFFICIAL-chiron.zip",
            "romtype": "unofficial",
            "datetime": 1618754135,
            "version": "17.1",
            "id": "95772cd1701d011d020ee673daef215799142a89ca007fb12dcff04a9ea49b57",
            "size": 763338807
        }
    ],
    "error": null
}
`

While checking ota updates, the lineagenos updater(version:lineage-17.1) reports error:
`
2021-04-18 22:12:12.291 1264-1264/system_process V/SettingsProvider: Notifying for 0: content://settings/system/screen_brightness
2021-04-18 22:12:13.010 5402-5402/org.lineageos.updater D/UpdatesActivity: Checking https://ota.xunt123.com/api
2021-04-18 22:12:14.229 5402-5402/org.lineageos.updater D/UpdatesActivity: List downloaded
2021-04-18 22:12:14.229 5402-5402/org.lineageos.updater D/UpdatesActivity: Adding remote updates
2021-04-18 22:12:14.233 5402-5402/org.lineageos.updater E/UpdatesActivity: Could not read json
    org.json.JSONException: No value for response
        at org.json.JSONObject.get(JSONObject.java:399)
        at org.json.JSONObject.getJSONArray(JSONObject.java:594)
        at org.lineageos.updater.misc.Utils.parseJson(Utils.java:133)
        at org.lineageos.updater.UpdatesActivity.loadUpdatesList(UpdatesActivity.java:246)
        at org.lineageos.updater.UpdatesActivity.processNewJson(UpdatesActivity.java:293)
        at org.lineageos.updater.UpdatesActivity.access$400(UpdatesActivity.java:70)
        at org.lineageos.updater.UpdatesActivity$4.lambda$onSuccess$1$UpdatesActivity$4(UpdatesActivity.java:338)
        at org.lineageos.updater.-$$Lambda$UpdatesActivity$4$Qra7D5MFC6cMp3CFdgMPYQ47iUw.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
`

It seems like  that the response json is not wanted.

**Comment by julianxhokaxhiu** [comment]
Hi, make sure the requirements are met. Additionally please test your API endpoint with the Unit Tester mentioned in the README. LOS 17.1 has already been tested by other users and worked successfully.

**Comment by LaiZhou** [comment]
@julianxhokaxhiu It's OK now. The api uri should be 
`
lineage.updater.uri=https://ota.xunt123.com/api/v1/{device}/{type}/{incr}

`
